"""autogenerated by genpy from roomba_500driver_meiji/LightBumper.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LightBumper(genpy.Message):
  _md5sum = "e47b16b189b712d59a52fb685a33acd1"
  _type = "roomba_500driver_meiji/LightBumper"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int8 bumper
int16 left
int16 front_left
int16 center_left
int16 center_right
int16 front_right
int16 right

"""
  __slots__ = ['bumper','left','front_left','center_left','center_right','front_right','right']
  _slot_types = ['int8','int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bumper,left,front_left,center_left,center_right,front_right,right

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LightBumper, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.bumper is None:
        self.bumper = 0
      if self.left is None:
        self.left = 0
      if self.front_left is None:
        self.front_left = 0
      if self.center_left is None:
        self.center_left = 0
      if self.center_right is None:
        self.center_right = 0
      if self.front_right is None:
        self.front_right = 0
      if self.right is None:
        self.right = 0
    else:
      self.bumper = 0
      self.left = 0
      self.front_left = 0
      self.center_left = 0
      self.center_right = 0
      self.front_right = 0
      self.right = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_b6h.pack(_x.bumper, _x.left, _x.front_left, _x.center_left, _x.center_right, _x.front_right, _x.right))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.bumper, _x.left, _x.front_left, _x.center_left, _x.center_right, _x.front_right, _x.right,) = _struct_b6h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_b6h.pack(_x.bumper, _x.left, _x.front_left, _x.center_left, _x.center_right, _x.front_right, _x.right))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.bumper, _x.left, _x.front_left, _x.center_left, _x.center_right, _x.front_right, _x.right,) = _struct_b6h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_b6h = struct.Struct("<b6h")
