/* Auto-generated by genmsg_cpp for file /home/kendemu/catkin_ws/src/roomba_robot_meiji/roomba_500driver_meiji/msg/Ir_Opcode.msg */
#ifndef ROOMBA_500DRIVER_MEIJI_MESSAGE_IR_OPCODE_H
#define ROOMBA_500DRIVER_MEIJI_MESSAGE_IR_OPCODE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace roomba_500driver_meiji
{
template <class ContainerAllocator>
struct Ir_Opcode_ {
  typedef Ir_Opcode_<ContainerAllocator> Type;

  Ir_Opcode_()
  : left(0)
  , right(0)
  {
  }

  Ir_Opcode_(const ContainerAllocator& _alloc)
  : left(0)
  , right(0)
  {
  }

  typedef int8_t _left_type;
  int8_t left;

  typedef int8_t _right_type;
  int8_t right;


  typedef boost::shared_ptr< ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator>  const> ConstPtr;
}; // struct Ir_Opcode
typedef  ::roomba_500driver_meiji::Ir_Opcode_<std::allocator<void> > Ir_Opcode;

typedef boost::shared_ptr< ::roomba_500driver_meiji::Ir_Opcode> Ir_OpcodePtr;
typedef boost::shared_ptr< ::roomba_500driver_meiji::Ir_Opcode const> Ir_OpcodeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace roomba_500driver_meiji

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> > {
  static const char* value() 
  {
    return "24825b8956c21f4c3dd28a5a4d09322c";
  }

  static const char* value(const  ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x24825b8956c21f4cULL;
  static const uint64_t static_value2 = 0x3dd28a5a4d09322cULL;
};

template<class ContainerAllocator>
struct DataType< ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> > {
  static const char* value() 
  {
    return "roomba_500driver_meiji/Ir_Opcode";
  }

  static const char* value(const  ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 left\n\
int8 right\n\
\n\
\n\
";
  }

  static const char* value(const  ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.left);
    stream.next(m.right);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Ir_Opcode_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::roomba_500driver_meiji::Ir_Opcode_<ContainerAllocator> & v) 
  {
    s << indent << "left: ";
    Printer<int8_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int8_t>::stream(s, indent + "  ", v.right);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROOMBA_500DRIVER_MEIJI_MESSAGE_IR_OPCODE_H

