/* Auto-generated by genmsg_cpp for file /home/kendemu/catkin_ws/src/roomba_robot_meiji/roomba_500driver_meiji/msg/LeftRight16.msg */
#ifndef ROOMBA_500DRIVER_MEIJI_MESSAGE_LEFTRIGHT16_H
#define ROOMBA_500DRIVER_MEIJI_MESSAGE_LEFTRIGHT16_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace roomba_500driver_meiji
{
template <class ContainerAllocator>
struct LeftRight16_ {
  typedef LeftRight16_<ContainerAllocator> Type;

  LeftRight16_()
  : right(0)
  , left(0)
  {
  }

  LeftRight16_(const ContainerAllocator& _alloc)
  : right(0)
  , left(0)
  {
  }

  typedef int16_t _right_type;
  int16_t right;

  typedef int16_t _left_type;
  int16_t left;


  typedef boost::shared_ptr< ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator>  const> ConstPtr;
}; // struct LeftRight16
typedef  ::roomba_500driver_meiji::LeftRight16_<std::allocator<void> > LeftRight16;

typedef boost::shared_ptr< ::roomba_500driver_meiji::LeftRight16> LeftRight16Ptr;
typedef boost::shared_ptr< ::roomba_500driver_meiji::LeftRight16 const> LeftRight16ConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace roomba_500driver_meiji

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5701c249118285e732313411c507131d";
  }

  static const char* value(const  ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5701c249118285e7ULL;
  static const uint64_t static_value2 = 0x32313411c507131dULL;
};

template<class ContainerAllocator>
struct DataType< ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> > {
  static const char* value() 
  {
    return "roomba_500driver_meiji/LeftRight16";
  }

  static const char* value(const  ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 right\n\
int16 left\n\
\n\
";
  }

  static const char* value(const  ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.right);
    stream.next(m.left);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LeftRight16_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::roomba_500driver_meiji::LeftRight16_<ContainerAllocator> & v) 
  {
    s << indent << "right: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right);
    s << indent << "left: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROOMBA_500DRIVER_MEIJI_MESSAGE_LEFTRIGHT16_H

