/* Auto-generated by genmsg_cpp for file /home/kendemu/catkin_ws/src/roomba_robot_meiji/roomba_500driver_meiji/msg/LightBumper.msg */
#ifndef ROOMBA_500DRIVER_MEIJI_MESSAGE_LIGHTBUMPER_H
#define ROOMBA_500DRIVER_MEIJI_MESSAGE_LIGHTBUMPER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace roomba_500driver_meiji
{
template <class ContainerAllocator>
struct LightBumper_ {
  typedef LightBumper_<ContainerAllocator> Type;

  LightBumper_()
  : bumper(0)
  , left(0)
  , front_left(0)
  , center_left(0)
  , center_right(0)
  , front_right(0)
  , right(0)
  {
  }

  LightBumper_(const ContainerAllocator& _alloc)
  : bumper(0)
  , left(0)
  , front_left(0)
  , center_left(0)
  , center_right(0)
  , front_right(0)
  , right(0)
  {
  }

  typedef int8_t _bumper_type;
  int8_t bumper;

  typedef int16_t _left_type;
  int16_t left;

  typedef int16_t _front_left_type;
  int16_t front_left;

  typedef int16_t _center_left_type;
  int16_t center_left;

  typedef int16_t _center_right_type;
  int16_t center_right;

  typedef int16_t _front_right_type;
  int16_t front_right;

  typedef int16_t _right_type;
  int16_t right;


  typedef boost::shared_ptr< ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roomba_500driver_meiji::LightBumper_<ContainerAllocator>  const> ConstPtr;
}; // struct LightBumper
typedef  ::roomba_500driver_meiji::LightBumper_<std::allocator<void> > LightBumper;

typedef boost::shared_ptr< ::roomba_500driver_meiji::LightBumper> LightBumperPtr;
typedef boost::shared_ptr< ::roomba_500driver_meiji::LightBumper const> LightBumperConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace roomba_500driver_meiji

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::roomba_500driver_meiji::LightBumper_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e47b16b189b712d59a52fb685a33acd1";
  }

  static const char* value(const  ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe47b16b189b712d5ULL;
  static const uint64_t static_value2 = 0x9a52fb685a33acd1ULL;
};

template<class ContainerAllocator>
struct DataType< ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> > {
  static const char* value() 
  {
    return "roomba_500driver_meiji/LightBumper";
  }

  static const char* value(const  ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 bumper\n\
int16 left\n\
int16 front_left\n\
int16 center_left\n\
int16 center_right\n\
int16 front_right\n\
int16 right\n\
\n\
";
  }

  static const char* value(const  ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.bumper);
    stream.next(m.left);
    stream.next(m.front_left);
    stream.next(m.center_left);
    stream.next(m.center_right);
    stream.next(m.front_right);
    stream.next(m.right);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LightBumper_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::roomba_500driver_meiji::LightBumper_<ContainerAllocator> & v) 
  {
    s << indent << "bumper: ";
    Printer<int8_t>::stream(s, indent + "  ", v.bumper);
    s << indent << "left: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left);
    s << indent << "front_left: ";
    Printer<int16_t>::stream(s, indent + "  ", v.front_left);
    s << indent << "center_left: ";
    Printer<int16_t>::stream(s, indent + "  ", v.center_left);
    s << indent << "center_right: ";
    Printer<int16_t>::stream(s, indent + "  ", v.center_right);
    s << indent << "front_right: ";
    Printer<int16_t>::stream(s, indent + "  ", v.front_right);
    s << indent << "right: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROOMBA_500DRIVER_MEIJI_MESSAGE_LIGHTBUMPER_H

