(cl:in-package roomba_500driver_meiji-msg)
(cl:export '(HEADER-VAL
          HEADER
          BUMP-VAL
          BUMP
          WHEELDROP-VAL
          WHEELDROP
          WALL-VAL
          WALL
          WALL_SIGNAL-VAL
          WALL_SIGNAL
          CLIFF-VAL
          CLIFF
          VIRTUAL_WALL-VAL
          VIRTUAL_WALL
          MOTOR_OVERCURRENTS-VAL
          MOTOR_OVERCURRENTS
          DIRT_DETECTOR-VAL
          DIRT_DETECTOR
          REMOTE_CONTROL_COMMAND-VAL
          REMOTE_CONTROL_COMMAND
          BUTTONS-VAL
          BUTTONS
          DISTANCE-VAL
          DISTANCE
          ANGLE-VAL
          ANGLE
          SONG-VAL
          SONG
          OPCODE-VAL
          OPCODE
          DIRT_DETECT-VAL
          DIRT_DETECT
          CHARGER_AVAILABLE-VAL
          CHARGER_AVAILABLE
          OPEN_INTERFACE_MODE-VAL
          OPEN_INTERFACE_MODE
          OI_STREAM_NUM_PACKETS-VAL
          OI_STREAM_NUM_PACKETS
          STASIS-VAL
          STASIS
          ENCODER_COUNTS-VAL
          ENCODER_COUNTS
          REQUESTED_WHEEL_VELOCITY-VAL
          REQUESTED_WHEEL_VELOCITY
          REQUESTED_VELOCITY-VAL
          REQUESTED_VELOCITY
          REQUESTED_RADIUS-VAL
          REQUESTED_RADIUS
          CHARGING_STATE-VAL
          CHARGING_STATE
          VOLTAGE-VAL
          VOLTAGE
          CURRENT-VAL
          CURRENT
          TEMPERATURE-VAL
          TEMPERATURE
          CHARGE-VAL
          CHARGE
          CAPACITY-VAL
          CAPACITY
          LIGHT_BUMPER-VAL
          LIGHT_BUMPER
))